In [1]:
import numpy as np

# Sample sentence
sentence = "The cat sat on the mat"

# Tokenize the sentence
tokens = sentence.lower().split()

# Build vocabulary
vocabulary = list(set(tokens))
vocab_size = len(vocabulary)

# Create a mapping from word to index
word_to_index = {word: idx for idx, word in enumerate(vocabulary)}

# One-hot encode each token
one_hot_vectors = np.zeros((len(tokens), vocab_size))

for i, token in enumerate(tokens):
    index = word_to_index[token]
    one_hot_vectors[i, index] = 1

print("Vocabulary:", vocabulary)
print("One-hot vectors:\n", one_hot_vectors)

Vocabulary: ['sat', 'the', 'cat', 'on', 'mat']
One-hot vectors:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
